version: '3.4'

services:
  perspace.api:
    image: ${DOCKER_REGISTRY-}perspaceapi
    build:
      context: .
      dockerfile: PerSpace.API/Dockerfile
    networks:
      - mynetwork

  reverseproxy:
    image: ${DOCKER_REGISTRY-}reverseproxy
    build:
      context: .
      dockerfile: ReverseProxy/Dockerfile
    networks:
      - mynetwork

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "6858212ASDzxc"
      ACCEPT_EULA: "Y"
    networks:
      - mynetwork

  backoffice:
    image: ${DOCKER_REGISTRY-}backoffice
    build:
      context: .
      dockerfile: BackOffice/Dockerfile
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
